name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: |
          docker-compose up -d

      - name: MongoDB status
        run: |
          docker-compose logs mongodb

      - name: Check MongoDB Connection Status
        run: |
          docker-compose exec -T mongodb mongo --eval 'db.runCommand({ connectionStatus: 1 })'

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdbus-1-3 \
            libxkbcommon0 \
            libgdk-pixbuf2.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libpangocairo-1.0-0 \
            libpango-1.0-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-asyncio playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright and browsers
        run: |
          python -m playwright install --with-deps

      - name: Verify Playwright installation
        run: |
          ls -al /home/runner/.cache/ms-playwright

      - name: Run tests with pytest
        env:
          MONGO_URI: mongodb://mongodb:27017/
        run: pytest

      - name: Tear down Docker Compose
        if: always()
        run: |
          docker-compose down

      - name: Deploy
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer ${DEPLOY_TOKEN}" http://your-deployment-service/deploy
